on : push
name : ğŸš€ Implementar website em
jobs push :
   web-deploy :
     name : ğŸ‰ Implementar
    runs-on : ubuntu-latest
    steps :
    - name : ğŸšš Obter o cÃ³digo mais recente
      usa : actions/checkout@v2.3.2

    - nome : ğŸ“‚ Os arquivos de sincronizaÃ§Ã£o
      usam : SamKirkland/FTP-Deploy-Action@4.0.0
      com :
         servidor : files.000webon: push
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v2.3.2

    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.samkirkland.com
        username: myFtpUserName
        password: ${{ secrets.ftp_password }}host.com
        nome de usuÃ¡rio : sistemahuges
        senha : $ {{SSH_SECRET}}