on : push
name : ğŸš€ Implementar website em
jobs push :
   web-deploy :
     name : ğŸ‰ Implementar
    runs-on : ubuntu-latest
    steps :
    - nome : ğŸšš Obter o cÃ³digo mais recente
      usa : actions/checkout@v2.3.2

    - nome : ğŸ“‚ Os arquivos de sincronizaÃ§Ã£o
      usam : SamKirkland/FTP-Deploy-Action@4.0.0
      com :
         servidor : files.000webhost.com
        nome de usuÃ¡rio : sistemahuges
        senha : $ {{SSH_SECRET}}